version: "3.9"

services:
  sge.postgres:
    image: postgres:latest # Utilise la dernière version officielle de PostgreSQL
    container_name: sge_postgres
    environment: # Variables d'environnement pour créer la DB + user
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432" # Expose le port pour accès depuis l'hôte (utile en dev)
    #volumes:
    #actuellement pas besoin de donnée persistante  - postgres_data:/var/lib/postgresql/data # Persistance des données
    networks:
      - sge_network

  sge.api:
    build:
      context: . # Contexte de build (racine de la solution)
      dockerfile: ../SGE/SGE.API/Dockerfile # Chemin vers le Dockerfile de l’API
    container_name: sge_api
    image: sge.api
    ports:
      - "8080:80" # Mappe le port 80 du conteneur sur 5000 de l’hôte
    depends_on:
      - sge.postgres # Démarre Postgres avant l’API (ordre, pas readiness)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword"
    networks:
      - sge_network

#volumes:
#  postgres_data: # Volume pour persister la BDD
#    driver: local

networks:
  sge_network:
    driver: bridge
